"""add is_archived to subjects

Revision ID: 25097ee3d1c1
Revises: 45c754783b46
Create Date: 2026-08-07 03:18:14.716216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25097ee3d1c1'
down_revision: Union[str, None] = '45c754783b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "subjects",
    sa.Column(
        "is_archived",
        sa.Boolean(),
        nullable=False,
        server_default=sa.false(),
    ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'is_archived')
    # ### end Alembic commands ###
