"""add locator_type to material_chunks

Revision ID: 46a6d313b6ad
Revises: d4eac8767747
Create Date: 2026-08-08 03:38:58.450489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46a6d313b6ad'
down_revision: Union[str, None] = 'd4eac8767747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_chunks', sa.Column('locator_type', sa.String(length=10), server_default='page', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_chunks', 'locator_type')
    # ### end Alembic commands ###
