"""add question_bank table

Revision ID: f6cb6f49c659
Revises: 46a6d313b6ad
Create Date: 2026-08-11 04:26:39.666915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6cb6f49c659'
down_revision: Union[str, None] = '46a6d313b6ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_bank',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('lesson', sa.String(length=150), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('bloom_level', sa.Enum('remembering', 'understanding', 'applying', 'analyzing', 'evaluating', 'creating', name='bloom_level_enum'), nullable=False),
    sa.Column('question_type', sa.Enum('multiple_choice', 'true_false', name='question_type_enum'), nullable=False),
    sa.Column('choices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('chroma_vector_id', sa.String(length=64), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['material_chunks.chunk_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('question_id'),
    sa.UniqueConstraint('chroma_vector_id')
    )
    op.create_index(op.f('ix_question_bank_subject_id'), 'question_bank', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_bank_subject_id'), table_name='question_bank')
    op.drop_table('question_bank')
    # ### end Alembic commands ###
