import uuid
from pathlib import Path
from typing import BinaryIO

from app.core.config import settings
from app.core.exceptions import AppError

CHUNK_SIZE = 1024 * 1024  # 1MB


def _resolve(storage_path: str) -> Path:
    # storage_path is always generated by us (never taken from client
    # input) so path traversal isn't really a live threat here - this is
    # cheap insurance in case that assumption ever stops being true.
    full = (Path(settings.STORAGE_ROOT) / storage_path).resolve()
    root = Path(settings.STORAGE_ROOT).resolve()
    if not str(full).startswith(str(root)):
        raise AppError(400, "invalid_storage_path", "Resolved path escapes storage root.")
    return full


def save_upload_stream(
    folder_id: uuid.UUID, material_id: uuid.UUID, extension: str, file_obj: BinaryIO
) -> tuple[str, int]:
    """Streams file_obj to disk in fixed-size chunks, enforcing
    MAX_UPLOAD_SIZE_MB as it goes rather than trusting the Content-Length
    header (which a client can lie about). Returns (storage_path,
    size_in_bytes). Raises AppError(413, "file_too_large", ...) and cleans
    up the partial file if the limit is exceeded."""
    relative_path = f"materials/{folder_id}/{material_id}{extension}"
    full_path = _resolve(relative_path)
    full_path.parent.mkdir(parents=True, exist_ok=True)

    max_bytes = settings.MAX_UPLOAD_SIZE_MB * 1024 * 1024
    total = 0

    try:
        with open(full_path, "wb") as out:
            while True:
                chunk = file_obj.read(CHUNK_SIZE)
                if not chunk:
                    break
                total += len(chunk)
                if total > max_bytes:
                    raise AppError(
                        413,
                        "file_too_large",
                        f"File exceeds the {settings.MAX_UPLOAD_SIZE_MB}MB limit.",
                    )
                out.write(chunk)
    except Exception:
        full_path.unlink(missing_ok=True)
        raise

    return relative_path, total


def get_absolute_path(storage_path: str) -> Path:
    return _resolve(storage_path)


def delete_file(storage_path: str) -> None:
    _resolve(storage_path).unlink(missing_ok=True)
