declare module "lucide-react" {
  import type { FC, SVGProps } from "react";
  export type LucideProps = SVGProps<SVGSVGElement> & {
    size?: number | string;
    absoluteStrokeWidth?: boolean;
    color?: string;
    strokeWidth?: number | string;
  };
  export type LucideIcon = FC<LucideProps>;
  const icons: Record<string, LucideIcon>;
  export default icons;
  export const LayoutDashboard: LucideIcon;
  export const FileText: LucideIcon;
  export const Search: LucideIcon;
  export const BarChart2: LucideIcon;
  export const Library: LucideIcon;
  export const Settings: LucideIcon;
  export const HelpCircle: LucideIcon;
  export const Bell: LucideIcon;
  export const Menu: LucideIcon;
  export const User: LucideIcon;
  export const Home: LucideIcon;
  export const BookOpenCheck: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const LogOut: LucideIcon;
  export const Plus: LucideIcon;
  export const Upload: LucideIcon;
  export const FolderOpen: LucideIcon;
  export const Trash2: LucideIcon;
  export const Archive: LucideIcon;
  export const X: LucideIcon;
  export const Check: LucideIcon;
  export const MoreHorizontal: LucideIcon;
  export const Moon: LucideIcon;
  export const Sun: LucideIcon;
  export const PanelLeftClose: LucideIcon;
  export const PanelLeftOpen: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const Info: LucideIcon;
  export const Filter: LucideIcon;
  export const Download: LucideIcon;
  export const Eye: LucideIcon;
  export const EyeOff: LucideIcon;
  export const Edit: LucideIcon;
  export const Copy: LucideIcon;
  export const Share2: LucideIcon;
  export const Calendar: LucideIcon;
  export const Clock: LucideIcon;
  export const MapPin: LucideIcon;
  export const Phone: LucideIcon;
  export const Mail: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const Star: LucideIcon;
  export const Heart: LucideIcon;
  export const Image: LucideIcon;
  export const Camera: LucideIcon;
  export const File: LucideIcon;
  export const Folder: LucideIcon;
  export const Grid: LucideIcon;
  export const List: LucideIcon;
  export const Lock: LucideIcon;
  export const Unlock: LucideIcon;
  export const Shield: LucideIcon;
  export const Zap: LucideIcon;
  export const Target: LucideIcon;
  export const Award: LucideIcon;
  export const Bookmark: LucideIcon;
  export const Tag: LucideIcon;
  export const Layers: LucideIcon;
  export const PieChart: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const TrendingDown: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ArrowUp: LucideIcon;
  export const ArrowDown: LucideIcon;
  export const ChevronsUpDown: LucideIcon;
  export const CircleDot: LucideIcon;
  export const XIcon: LucideIcon;
  export const ScanLine: LucideIcon;
  export const FileUp: LucideIcon;
  export const GraduationCap: LucideIcon;
  export const ClipboardList: LucideIcon;
  export const Brain: LucideIcon;
  export const Lightbulb: LucideIcon;
}
